import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="manifest" href="/manifest.json" />
        {/* Add other meta tags, link tags, etc. */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
